title: P4-Forch_KatharaTopo
description: "Exploiting Data Plane Programmability to Enhance Service Orchestration in the Edge: a focus on Industrial Security."
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
