title: Orchestration for Industrial Security in the Edge, simulated with Kathara
description: "Exploiting Data Plane Programmability to Enhance Service Orchestration in the Edge: a focus on Industrial Security."
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
